blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Yash159357/BlyFt/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🌐 Discord Community
    url: https://discord.gg/nVKvVqWEwX
    about: Connect with the community, share ideas, and discuss features.
