name: 🔧 Other
description: For issues that don't fit into other categories
title: "[OTHER] - "
labels: ["gssoc2025", "hacktoberfest-accepted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to BlyFt! If your issue doesn't fit into our other categories, please use this template.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the project documentation and contributing guidelines
          required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of your issue
      placeholder: Describe your issue, question, or topic for discussion...
    validations:
      required: true


  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for addressing this issue, describe them here
      placeholder: Describe any potential solutions or approaches you've considered...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: Include any other relevant details, screenshots, or context...
